#ifndef ORBIT_H
#define ORBIT_H

/* Auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct OrbitApp OrbitApp;

typedef void (*OrbitDataCallback)(const char*, const uint8_t*, size_t, void*);

typedef void (*OrbitClosedCallback)(const char*, void*);

typedef void (*OrbitProgressCallback)(const char*, uint64_t, uint64_t, void*);

ORBIT_API struct OrbitApp *orbit_app_new(const char *db_path);

ORBIT_API void orbit_app_free(struct OrbitApp *app);

ORBIT_API int32_t orbit_list_servers(struct OrbitApp *app, char **out_json);

ORBIT_API int32_t orbit_add_server(struct OrbitApp *app, const char *json_input, char **out_json);

ORBIT_API int32_t orbit_update_server(struct OrbitApp *app, const char *id, const char *json_input, char **out_json);

ORBIT_API int32_t orbit_delete_server(struct OrbitApp *app, const char *id);

ORBIT_API int32_t orbit_list_credential_groups(struct OrbitApp *app, char **out_json);

ORBIT_API int32_t orbit_add_credential_group(struct OrbitApp *app, const char *json_input, char **out_json);

ORBIT_API int32_t orbit_update_credential_group(struct OrbitApp *app, const char *id, const char *json_input, char **out_json);

ORBIT_API int32_t orbit_delete_credential_group(struct OrbitApp *app, const char *id);

ORBIT_API int32_t orbit_test_connection(struct OrbitApp *app, const char *json_input);

ORBIT_API int32_t orbit_connect_ssh(struct OrbitApp *app, const char *server_id, OrbitDataCallback data_cb, OrbitClosedCallback closed_cb, void *userdata, char **out_session_id);

ORBIT_API int32_t orbit_write_ssh(struct OrbitApp *app, const char *session_id, const uint8_t *data, size_t data_len);

ORBIT_API int32_t orbit_resize_ssh(struct OrbitApp *app, const char *session_id, uint32_t cols, uint32_t rows);

ORBIT_API int32_t orbit_disconnect_ssh(struct OrbitApp *app, const char *session_id);

ORBIT_API int32_t orbit_get_ssh_traffic(struct OrbitApp *app, const char *session_id, uint64_t *out_read, uint64_t *out_written);

ORBIT_API int32_t orbit_sftp_list(struct OrbitApp *app, const char *server_id, const char *path, char **out_json);

ORBIT_API int32_t orbit_sftp_list_fast(struct OrbitApp *app, const char *server_id, const char *path, char **out_json);

ORBIT_API int32_t orbit_sftp_stat_dir_entries(struct OrbitApp *app, const char *server_id, const char *path, char **out_json);

ORBIT_API int32_t orbit_sftp_download(struct OrbitApp *app, const char *server_id, const char *remote_path, const char *local_path, OrbitProgressCallback progress_cb, void *userdata);

ORBIT_API int32_t orbit_sftp_upload(struct OrbitApp *app, const char *server_id, const char *local_path, const char *remote_path, OrbitProgressCallback progress_cb, void *userdata);

ORBIT_API int32_t orbit_sftp_mkdir(struct OrbitApp *app, const char *server_id, const char *path);

ORBIT_API int32_t orbit_sftp_remove(struct OrbitApp *app, const char *server_id, const char *path, bool is_dir);

ORBIT_API int32_t orbit_sftp_disconnect(struct OrbitApp *app, const char *server_id);

ORBIT_API int32_t orbit_get_server_stats(struct OrbitApp *app, const char *server_id, char **out_json);

ORBIT_API int32_t orbit_get_server_home(struct OrbitApp *app, const char *server_id, char **out_home);

ORBIT_API void orbit_free_string(char *s);

#endif  /* ORBIT_H */
